// Copyright Universe Project. All Rights Reserved.

#include "PlanetSurface.h"
#include "UniverseHash.h"
#include "StarSystemGenerator.h"

namespace
{
    /** Folds a double into a hash by its bit pattern, not its value. */
    uint64 HashDouble(uint64 Accumulator, double Value)
    {
        uint64 Bits = 0;
        const unsigned char* Source = reinterpret_cast<const unsigned char*>(&Value);
        for (size_t Index = 0; Index < sizeof(double); ++Index)
        {
            Bits |= static_cast<uint64>(Source[Index]) << (Index * 8);
        }
        return UniverseHash::Combine(Accumulator, Bits);
    }
}

FPlanetSurfaceDescriptor FPlanetSurfaceDescriptor::FromGeneratedPlanet(
    const FStarSystemDescriptor& System,
    int32 InOrbitIndex)
{
    FPlanetSurfaceDescriptor Surface;

    if (!System.Planets.IsValidIndex(InOrbitIndex))
    {
        return Surface;
    }

    const FPlanetDescriptor& Planet = System.Planets[InOrbitIndex];

    Surface.SystemId = System.Id;
    Surface.OrbitIndex = InOrbitIndex;
    Surface.PlanetKey =
        UniverseHash::Hash(0x504C414E45540001ull, System.Id.Hash, InOrbitIndex) | 1ull;

    // Terrain descends from the body seed through the Surface domain, so the
    // shape of the ground is independent of the star, mass and orbit values
    // drawn from the same body seed. Adding a physical property to a planet
    // later must not move its mountains.
    Surface.Seed = Planet.Seed.Stream(UniverseSeedDomain::StreamSurface);

    // The astronomical descriptor is the single source of truth for radius and
    // position; nothing here re-derives them.
    Surface.RadiusMeters = Planet.RadiusMeters;
    Surface.Position = FStarSystemGenerator::GetPlanetPosition(System, Planet);

    // Relief scales with the body rather than being a constant. Earth's highest
    // peak is about 0.14% of its radius and its deepest trench about 0.17%; a
    // fixed 9 km would give a small moon Himalayas and a gas giant a
    // billiard-ball surface.
    //
    // Scaled up slightly from the Earth ratios because a planet that is
    // geometrically accurate is also visually almost flat, and Sprint 002 needs
    // relief to be legible while it is being validated.
    constexpr double ElevationFraction = 0.0030;
    constexpr double DepthFraction = 0.0035;

    Surface.MaxElevationMeters = Planet.RadiusMeters * ElevationFraction;
    Surface.MaxDepthMeters = Planet.RadiusMeters * DepthFraction;

    Surface.GenerationVersion = PlanetTerrainVersion::Current;

    return Surface;
}

void FPlanetSurfaceDescriptor::Serialize(FUniverseByteWriter& Writer) const
{
    SystemId.Serialize(Writer);
    Writer.WriteInt32(OrbitIndex);
    Writer.WriteUInt64(PlanetKey);
    Writer.WriteUInt64(Seed.Value);
    Position.Serialize(Writer);
    Writer.WriteDouble(RadiusMeters);
    Writer.WriteDouble(MaxElevationMeters);
    Writer.WriteDouble(MaxDepthMeters);
    Writer.WriteUInt32(GenerationVersion);
}

bool FPlanetSurfaceDescriptor::Deserialize(FUniverseByteReader& Reader)
{
    FPlanetSurfaceDescriptor Candidate;

    if (!Candidate.SystemId.Deserialize(Reader))
    {
        return false;
    }

    Candidate.OrbitIndex = Reader.ReadInt32();
    Candidate.PlanetKey = Reader.ReadUInt64();
    Candidate.Seed = FUniverseSeed(Reader.ReadUInt64());

    if (!Candidate.Position.Deserialize(Reader))
    {
        return false;
    }

    Candidate.RadiusMeters = Reader.ReadDouble();
    Candidate.MaxElevationMeters = Reader.ReadDouble();
    Candidate.MaxDepthMeters = Reader.ReadDouble();
    Candidate.GenerationVersion = Reader.ReadUInt32();

    if (!Reader.IsValid() || !Candidate.IsValid())
    {
        return false;
    }

    *this = Candidate;
    return true;
}

uint64 FPlanetSurfaceDescriptor::GetContentHash() const
{
    // Everything that affects terrain shape, and nothing that does not.
    // GenerationVersion is included deliberately: a planet generated by a
    // different version of the algorithm is a different planet, and the hash
    // should say so.
    uint64 Hash = UniverseHash::Mix64(0x504C4E5453524600ull);  // "PLNTSRF"
    Hash = UniverseHash::Combine(Hash, PlanetKey);
    Hash = UniverseHash::Combine(Hash, Seed.Value);
    Hash = HashDouble(Hash, RadiusMeters);
    Hash = HashDouble(Hash, MaxElevationMeters);
    Hash = HashDouble(Hash, MaxDepthMeters);
    Hash = UniverseHash::Combine(Hash, GenerationVersion);
    return Hash;
}

FString FPlanetSurfaceDescriptor::ToDebugString() const
{
    return FString::Printf(
        TEXT("Planet %s #%d key=0x%016llX seed=0x%016llX  r=%.1f km  relief +%.0f/-%.0f m  gen v%u"),
        *SystemId.ToDebugString(),
        OrbitIndex,
        static_cast<unsigned long long>(PlanetKey),
        static_cast<unsigned long long>(Seed.Value),
        RadiusMeters / 1000.0,
        MaxElevationMeters,
        MaxDepthMeters,
        GenerationVersion);
}
